# Generated by Django 5.1.1 on 2024-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=50)),
                ('alumno_fono', models.CharField(max_length=12)),
                ('alumno_ingreso', models.CharField(max_length=12)),
                ('alumno_carrera', models.CharField(max_length=30)),
                ('alumno_observacion', models.CharField(max_length=500)),
            ],
        ),
    ]
